[application]

[web.app]

# HTML title tag content
title = "posot_thai"
# แก้ไข: เปลี่ยนจาก "/posot_thai/" เป็น "/" เพื่อให้เข้าผ่าน localhost:8080 ได้โดยตรง
base_path = "/"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []